### PR TITLE
Upload testpoint map on behalf of BBC

### PR DESCRIPTION
**Pull request by jaustin**
This file is (C) British Broadcasting Corporation and released on behalf of the BBC under the same license as the rest of the contents of this repository. I am uploading on behalf of the BBC.

The test point map is useful in conjunction with the schematic for knowing where the test signals are routed to.

### CODE REVIEW

**Comment by dpgeorge** [comment]
+1

**Comment by microbit-mark** [comment]
micro:bit-support:4231

Request from user to have this merged. Anything holding it back? @jaustin did i see that this had recently been updated?

**Comment by carlosperate** [comment]
There needs to be some clarification text added to the file, but once that's done it should be good to merge.

**Comment by nealmcb** [comment]
Here is some clarification text that seems appropriate, based off of the schematics, as annotated at [Test point map for BBC micro:bit \- Electrical Engineering Stack Exchange](https://electronics.stackexchange.com/questions/373780/test-point-map-for-bbc-microbit)

```
The signal names are as follows, according to the schematic.

 1 TMS  -- Debug interface for KL26
 2 TDO  --  "
 3 TDI  --  "
 4 TCLK --  "
 5 RST* --  "
 6 TGT_SWDIO
 7 TGT_SWCLK
 8 KL26 XTAL -- has 16MHz sine wave
 9 GND
10 VBUS_IF -- carries 5V when USB plugged in
11 USB-D+
12 USB-D-
13 VBAT
14 +V_TGT
15 TGT_TX -- UART transmit from nRF51
16 +3.3V_IF
17 TGT_RX -- UART receive from nRF51
18 VBAT
19 GND
20 TGT_RESET
21 GND
22 GND
```

Please do merge this so it gets wider exposure. I was lucky to wander across that post when I was looking.

**Pull request merged**
